config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/", to: "home#index"
  resources :projets

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/description_complete.rb
class DescriptionComplete < ApplicationRecord
  belongs_to :projet
end

app/models/projet.rb
class Projet < ApplicationRecord
  has_one :description_complete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController

  def index
    @projets = Projet.all
  end

  def show
    @projet = Projet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/home/index.html.erb
<%= javascript_include_tag "custom/homepage.js", defer: true %>
<%= stylesheet_link_tag "pages/homepage.css" %>
<%# <audio src="./assets/Tentative 2(mixed).wav" controls preload></audio> %>
<div class="hero-section">
  <div class="container hero-container">
    <div class="text-container">
      <h1>Z Corp</h1>
      <p>La Z corp est une équipe de super crackito, réalisant des sites internet uniques
      et des applications incroyables pour le plaisir de TOUT LE MONDE.</p>
    </div>
    <img class="homepage-image" src="https://picsum.photos/200" alt="">
  </div>

</div>

<div class="container">
  <h2><span class="cta"><%= link_to "Voir nos projets ->", "/projets" %></span></h2>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "custom/curseur.js", defer: true %>
  </head>

  <body>
  <%= render "shared/header" %>
  <%= render "shared/curseur" %>
    <%= yield %>
    
  </body>
</html>

app/views/projets/index.html.erb
<%= javascript_include_tag "custom/projetIndex.js", defer: true %>
<%# <audio src="/assets/Le Lobby.wav" controls ></audio> %>
<div class="container">
  <h1>Liste des projets:</h1>
  <div class="sub-container">
    <% @projets.each do |projet| %>
      <div class="carte-projet">
        <div class="section-carousel">
          <div class="carousel">
            <button class="carousel-nav"><</button>
            <button class="carousel-nav">></button>
          </div>
          <div class="carte-titre">
          <span class="titre-projet">
            <h2><%= projet.nom %></h2>
          </span>
          </div>
        </div>
      <div class="section-description">
        <div class="description"> <%= projet.descriptionR %></div>
        <span class="btn-projet"><%= link_to "En savoir plus", projet_path(projet) %></span>
      </div>
    </div>
    <% end %>
</div>

app/views/projets/show.html.erb
<%= javascript_include_tag("custom/projetShow.js") %>
<h1><%= @projet.nom %></h1>
<p><%= @projet.descriptionC %></p>
<a href="<% @projet.images_process_url %>" target="_blank"></a>

app/views/shared/_curseur.html.erb
<div class="cursor"></div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="logo">
    <h2>Zcorp</h2>
  </div>
  <div class="link-box">
  <div class="nav-link"><%= link_to_unless_current "Accueil", "/" %></div>
  <div class="nav-link"><%= link_to_unless_current "Projets", "/projets" %></div>
  <div class="nav-link"><%= link_to_unless_current "Contact", "#"%></div>
  </div>
</div>